from enum import Enum

class UserRole(str, Enum):
    STUDENT = "student"
    TEACHER = "teacher"
    ADMIN = "admin"

class IdentifierType(str, Enum):
    NISN = "NISN"
    NUPTK = "NUPTK"
    NIP = "NIP"
    NPSN = "NPSN"
    TEACHER_SSO = "TEACHER_SSO"
    EMAIL = "EMAIL"

class UserStatus(str, Enum):
    ACTIVE = "active"
    DISABLED = "disabled"

class AuditEventType(str, Enum):
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
    AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED"

    # Phase 4 Portfolio & Evidence Events
    PORTFOLIO_CREATED = "PORTFOLIO_CREATED"
    PORTFOLIO_UPDATED = "PORTFOLIO_UPDATED"
    PORTFOLIO_SUBMITTED = "PORTFOLIO_SUBMITTED"
    PORTFOLIO_REVISION_STARTED = "PORTFOLIO_REVISION_STARTED"
    PORTFOLIO_RESUBMITTED = "PORTFOLIO_RESUBMITTED"
    EVIDENCE_UPLOAD_CREATED = "EVIDENCE_UPLOAD_CREATED"
    EVIDENCE_UPLOAD_COMPLETED = "EVIDENCE_UPLOAD_COMPLETED"
    EVIDENCE_UPLOAD_REJECTED = "EVIDENCE_UPLOAD_REJECTED"
    EVIDENCE_DELETED = "EVIDENCE_DELETED"

    # Phase 5 Teacher Validation & Rubrics Events
    AUTH_RBAC_CHALLENGE = "AUTH_RBAC_CHALLENGE"
    PORTFOLIO_APPROVED = "PORTFOLIO_APPROVED"
    PORTFOLIO_REVISION_REQUESTED = "PORTFOLIO_REVISION_REQUESTED"
    PORTFOLIO_REJECTED = "PORTFOLIO_REJECTED"
    PORTFOLIO_REVIEW_OPENED = "PORTFOLIO_REVIEW_OPENED"

    # Phase 6 School Administration Events
    ADMIN_USER_CREATED = "ADMIN_USER_CREATED"
    ADMIN_USER_UPDATED = "ADMIN_USER_UPDATED"
    ADMIN_USER_DISABLED = "ADMIN_USER_DISABLED"
    ADMIN_USER_REACTIVATED = "ADMIN_USER_REACTIVATED"
    ADMIN_PASSWORD_RESET = "ADMIN_PASSWORD_RESET"
    ADMIN_CLASS_CREATED = "ADMIN_CLASS_CREATED"
    ADMIN_CLASS_UPDATED = "ADMIN_CLASS_UPDATED"
    ADMIN_CLASS_ARCHIVED = "ADMIN_CLASS_ARCHIVED"
    ADMIN_ENROLLMENT_CHANGED = "ADMIN_ENROLLMENT_CHANGED"
    ADMIN_TEACHER_ASSIGNMENT_CHANGED = "ADMIN_TEACHER_ASSIGNMENT_CHANGED"

    # Phase 7 Career Recommendation & Industry Translator Events
    RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED"
    RECOMMENDATION_REFRESHED = "RECOMMENDATION_REFRESHED"
    PROFESSIONAL_DESCRIPTION_GENERATED = "PROFESSIONAL_DESCRIPTION_GENERATED"
    TRANSLATOR_FALLBACK_USED = "TRANSLATOR_FALLBACK_USED"

    # Phase 8 Production Digital CV & Public Verification Events
    CV_SNAPSHOT_CREATED = "CV_SNAPSHOT_CREATED"
    CV_PDF_RENDERED = "CV_PDF_RENDERED"
    CV_VERIFICATION_ISSUED = "CV_VERIFICATION_ISSUED"
    CV_VERIFICATION_REVOKED = "CV_VERIFICATION_REVOKED"
    CV_DOWNLOAD_ACCESSED = "CV_DOWNLOAD_ACCESSED"
    CV_PUBLIC_VERIFICATION_CHECKED = "CV_PUBLIC_VERIFICATION_CHECKED"


class VerificationStatus(str, Enum):
    ACTIVE = "active"
    REVOKED = "revoked"
    EXPIRED = "expired"


class CVIssuanceStatus(str, Enum):
    PREPARING = "preparing"
    ISSUED = "issued"
    FAILED = "failed"
    REVOKED = "revoked"


